apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: jenkins-argo-cronworkflow-manager
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["cronworkflows"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]           # optional but usually needed
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
